language: generic
sudo: required #sudo means admin permission
services:
  - docker

before-install:
  - docker build -t suhaasnandeesh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true suhaasnandeesh/docker-react npm run test