language: generic #to remove rake not found error
sudo: required #sudo means admin permission
services:
  - docker

before_install:
  - docker build -t suhaasnandeesh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true suhaasnandeesh/docker-react npm run test