language: generic #to remove rake not found error
sudo: required #sudo means admin permission
services:
  - docker

before_install:
  - docker build -t suhaasnandeesh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true suhaasnandeesh/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  app: "docker-react"
  env: "DockerReact-env"
  region: "us-east-1"
  bucket_name: "elasticbeanstalk-us-east-1-189715679283"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"